homeassistant:
  # Name of the location where Home Assistant is running
  name: Otthon
  # Location required to calculate the time the sun rises and sets
  latitude: 46.83
  longitude: 16.82
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 152
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest
  # Customization file
  customize: !include customize.yaml

influxdb:

frontend:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
#frontend:

# Enables configuration UI
config:

climate:
  - platform: generic_thermostat
    name: Szoba Termosztát
    heater: switch.szoba_futopanel
    target_sensor: sensor.homerseklet_szoba

http:
   api_password: !secret http_password
   ssl_certificate: /etc/letsencrypt/live/whiterhass.duckdns.org/fullchain.pem
   ssl_key: /etc/letsencrypt/live/whiterhass.duckdns.org/privkey.pem
   base_url: whiterhass.duckdns.org:443

mqtt:
  broker: localhost
  keepalive: 60

device_tracker:
  - platform: snmp
    host: 11.10.0.1
    community: public
    baseoid: 1.3.6.1.2.1.4.22.1.2
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False

media_player:
  - platform: kodi
    host: 10.10.0.128
  - platform: yamaha
    host: 10.10.1.17
    source_ignore:
      - "AUX"
      - "HDMI6"
      - "USB"
      - "TUNER"
      - "SERVER"
      - "Qobuz"
      - "NET RADIO"
      - "JUKE"
      - "HDMI1"
      - "HDMI3"
      - "HDMI4"
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AUX"
      - "AirPlay"
      - "Bluetooth"
      - "MusicCast Link"
    source_names:
      HDMI2: "FireTV Stick"
  - platform: samsungtv
    host: 192.168.0.119
  - platform: spotify
    client_id: 203125f9bdc249888078b8c7e3b95b72
    client_secret: af391b3da3f74101a81aaa1880abaf8c

switch 8:
  - platform: broadlink
    host: 10.10.1.15
    mac: '34:EA:34:D0:AC:E9'
    type: rm
    switches:
      yamaha:
        friendly_name: "Yamaha Receiver"
        command_on: 'JgBQAAABKJIVEBQ1FTUVNBU1FjQUNRUQFTUUEBUQFRAVEBQRFBAVNRUQFDUVEBU1FBEUNRYPFBEUNRYPFTUUEBU1FRAUNRY0FgAFGgABKUcWAA0FAAAAAAAAAAA='
        command_off: 'JgBQAAABKJIVEBQ1FTUVNBU1FjQUNRUQFTUUEBUQFRAVEBQRFBAVNRUQFDUVEBU1FBEUNRYPFBEUNRYPFTUUEBU1FRAUNRY0FgAFGgABKUcWAA0FAAAAAAAAAAA='
      benq:
        friendly_name: "Benq Projector"
        command_on: 'JgDYAAABJ5EUEBQRFBEUEBUQFBAUERQRExEUERQQFRAUNRU0FBEUEBQ1FTQVNRQ1FBAUERU0FRAUEBQRFBAUERU0FDUVEBQ1FQAF7wABKJAVEBUQFBAVEBUQFBAUERQQFRAVEBQQFRAUNRU0FRAUEBU0FTQVNBU0FRAVEBQ1FQ8VEBQRFBAVEBQ1FTQVEBQ1FAAF8AABKJAVEBUQFBAUERUPFRAUERQQFRAVDxUQFRAUNRQ1FQ8VEBU0FTQVNBU0FRAVEBQ1FBAVEBUQFBAVEBQ1FTQVEBQ1FAANBQ=='
        command_off: 'JgCQAAABJ5EVEBQRExEVEBQQFBEUEBUQFBEUEBUQFQ8VNBU1FBAVEBQQFDUVNRQ1FBAVEBQ1FRAUNRQQFBEVDxQ1FTUUEBU0FQAF8AABJ5EVDxUQFRAUEBUQFQ8VEBUQFBAVEBQQFBEVNBU0FRAUEBQRFTQVNBU0FRAUEBU0FRAVNBUQFQ8VEBU0FTQVEBQ1FQANBQAAAAAAAAAA'
        
notify:
  - name: pushover-noti
    platform: pushover
    api_key: ay1uf5zuhuj6fmkum5bxddirq3ijuh
    user_key: uzo3mbrfe7n9u697xbimdohgy4yyzw

emulated_hue:
  host_ip: 10.10.0.22
  listen_port: 8300
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - script

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#wemo:

# Track the sun
sun:

#switch:
#  platform: mqtt
#  name: "Switch"
#  state_topic: "whit33r/sonoff1"
#  command_topic: "/whit33r/kitchen/sonoff1"
#  payload_on: "ON"
#  payload_off: "OFF"
#  optimistic: true
#  qos: 1
 # retain: true
  #value_template: '{{ value.x }}'

switch:
  platform: mqtt
  name: "Folyosó Világítás"
  icon: mdi:lightbulb
  alias: "folyoso_light"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 2:
  platform: mqtt
  name: "Konyha Világítás"
  icon: mdi:lightbulb
  alias: "kitchen_light"
  state_topic: "home/sonoff/kitchen/1/stat"
  command_topic: "home/sonoff/kitchen/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 3:
  platform: mqtt
  name: "Szoba Fűtőpanel"
  alias: "heater test"
  state_topic: "home/sonoff/heater/1/stat"
  command_topic: "home/sonoff/heater/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 5:
  platform: mqtt
  name: "Fogyasztásmérő"
  state_topic: "home/sonoff/pwrHeater/1/stat"
  command_topic: "home/sonoff/pwrHeater/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 4:
  platform: mqtt
  name: "Szoba Világítás"
  icon: mdi:lightbulb
  alias: "szoba_vilagitas"
  state_topic: "home/sonoff/room/1/stat"
  command_topic: "home/sonoff/room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 5:
  platform: mqtt
  name: "test"
  state_topic: "home/sonoff/test/1/stat"
  command_topic: "home/sonoff/test/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

        
script:
  mozi_bekapcsolasa:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.yamaha
      - delay: '00:00:01'
      - service: switch.turn_on
        data:
          entity_id: switch.benq
      - delay: '00:00:02'
      - service: media_player.select_source
        data:
          entity_id: media_player.yamaha_receiver
          source: FireTV Stick

  mozi_kikapcsolasa:
    sequence:
      - service: switch.turn_off
        data:
          entity_id: switch.yamaha
      - delay: '00:00:01'
      - service: switch.turn_off
        data:
          entity_id: switch.benq
      - delay: '00:00:01'
      - service: switch.turn_off
        data:
          entity_id: switch.benq
  
scene:
  - name: night_on
#    friendly_name: night_light
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 1
       rgb_color: [0, 0, 255]
  - name: night_off
#    friendly_name: night_light
    entities:
      light.szoba_vilagitas:
       state: off
  - name: dim_up_movie
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 250
       rgb_color: [255, 255, 255]
       transition: 5
  - name: dim_down_movie
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 2
       rgb_color: [0, 0, 255]
       transition: 5
  - name: media_on
    entities:
      switch.yamaha:
        state: on



group:
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - group.room
      - group.kitchen
      - group.hallway
      - group.climate
      - group.power
      - group.media
#      - group.awesome_people
  room:
    name: Szoba
    entities:
#      - light.karacsonyfa
#      - light.kis_karacsonyfa
      - light.szoba_hangulatfeny
      - switch.szoba_vilagitas
#      - switch.test
      - sensor.szoba_lux
      - automation.When_lightoff_lockoff
      - automation.When_lighton_lockoff
      - script.mozi_bekapcsolasa
      - script.mozi_kikapcsolasa
#      - climate.study
#      - scene.dim_up_movie
#      - scene.dim_down_movie
#      - automation.media_player_pausedstopped
#      - automation.media_player_pausedstopped_
  kitchen:
    name: Konyha
#    view: no
    entities:
      - switch.konyha_vilagitas
  hallway:
    name: Folyosó
    entities:
      - switch.folyoso_vilagitas
      - binary_sensor.bejarati_ajto
      - binary_sensor.bejarati_ajto_zar
      - binary_sensor.mozgaserzekelo
#  upstairs:
#    name: Kids
#    icon: mdi:account-multiple
#    view: yes
#    entities:
#      - input_boolean.notify_home
#      - camera.demo_camera
#      - device_tracker.demo_paulus
#      - group.garden
  climate:
    name: Hőmérséklet
    view: no
    entities:
      - sensor.homerseklet_szoba
      - sensor.homerseklet_konyha
      - sensor.homerseklet_kulso
      - climate.szoba_termosztat
      - switch.szoba_futopanel
      - switch.fogyasztasmero
  power:
    name: Fogyasztás
#    view: no
    entities:
      - sensor.volt
      - sensor.jelenlegi_teljesitmeny
      - sensor.ossz_fogyasztas
  media:
    name: Média Eszközök
#    view: no
    entities:
      - media_player.kodi
      - media_player.spotify
      - media_player.yamaha_receiver
  awesome_people:
    name: Emberek
    view: no
    entities:
      - device_tracker.lg_g4lan
      - device_tracker.whit33r_samsung_s7lan
      
    
alexa:

intent_script: !include alexa_intents.yaml

# Text to speech
#tts:
#  - platform: google

automation: !include automation.yaml
#script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include light.yaml
binary_sensor: !include binary_sensor.yaml

