homeassistant:
  # Name of the location where Home Assistant is running
  name: Otthon
  # Location required to calculate the time the sun rises and sets
  latitude: 46.83
  longitude: 16.82
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 152
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Budapest
  # Customization file
  customize: !include customize.yaml

influxdb:

frontend:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
#frontend:

# Enables configuration UI
config:

climate:
  - platform: generic_thermostat
    name: Szoba Termosztát
    heater: switch.szoba_futopanel
    target_sensor: sensor.homerseklet_szoba

http:
   api_password: !secret http_password
#   ssl_certificate: /etc/letsencrypt/live/whiterhass.duckdns.org/fullchain.pem
#   ssl_key: /etc/letsencrypt/live/whiterhass.duckdns.org/privkey.pem
#   base_url: whiterhass.duckdns.org:443

mqtt:
  broker: localhost
  keepalive: 60

device_tracker:
  - platform: snmp
    host: 11.10.0.1
    community: public
    baseoid: 1.3.6.1.2.1.4.22.1.2
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False

media_player:
  - platform: kodi
    host: 10.10.0.128
  - platform: yamaha
    host: 10.10.0.19
  - platform: samsungtv
    host: 192.168.0.119
  - platform: spotify
    client_id: 203125f9bdc249888078b8c7e3b95b72
    client_secret: af391b3da3f74101a81aaa1880abaf8c

switch 8:
  - platform: broadlink
    host: 10.10.0.53
    mac: '34:EA:34:D0:AC:E9'
    type: rm

notify:
  - name: pushover-noti
    platform: pushover
    api_key: ay1uf5zuhuj6fmkum5bxddirq3ijuh
    user_key: uzo3mbrfe7n9u697xbimdohgy4yyzw

emulated_hue:
  host_ip: 10.10.0.22
  listen_port: 8300
  off_maps_to_on_domains:
    - script
  expose_by_default: true
  exposed_domains:
    - light
    - switch

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

#wemo:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Időjárás

sensor 2:
  platform: mqtt
  name: "Hőmérséklet Konyha"
  state_topic: "/home/temp/kitchen"
  qos: 0
  force_update: true
  unit_of_measurement: "°C"

sensor 3:
  platform: mqtt
  name: "Hőmérséklet Szoba"
  state_topic: "/home/temp/room"
  qos: 0
  force_update: true
  unit_of_measurement: "°C"

sensor 4:
  platform: mqtt
  name: "Hőmérséklet Külső"
  state_topic: "/home/temp/outside"
  qos: 0
  force_update: true
  unit_of_measurement: "°C"

sensor 5:
  platform: mqtt
  name: "Volt"
  state_topic: "sonoff/volt"
  unit_of_measurement: "V"
  force_update: true

sensor 6:
  platform: mqtt
  name: "Jelenlegi Teljesítmény"
  state_topic: "sonoff/power"
  unit_of_measurement: "W"
  force_update: true

sensor 7:
  platform: mqtt
  name: "Össz Fogyasztás"
  state_topic: "sonoff/totalenergy"
  unit_of_measurement: "kWh"
  force_update: true

sensor 8:
  platform: mqtt
  name: "Szoba Lux"
  state_topic: "room/ambient_light"
  unit_of_measurement: "Lux"
  force_upcate: true

light:
  - platform: mqtt_json
    name: "Szoba Hangulatfény"
 #   fiendly_name: "Szoba Világítás"
    state_topic: "whit33r/stripUp"
    command_topic: "whit33r/stripUp/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

light 2:
  - platform: mqtt_json
    name: "Kis Karácsonyfa"
    state_topic: "whit33r/strip_test"
    command_topic: "whit33r/strip_test/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

light 3:
  - platform: mqtt_json
    name: "Karácsonyfa"
    alias: "Karácsonyfa"
    state_topic: "whit33r/christmas_light1"
    command_topic: "whit33r/room/christmas_light1"
    brightness: true
    optimistic: false
    qos: 0

light 4:
  - platform: mqtt_json
    name: "Switch"
    state_topic: "whit33r/sonoff1"
    command_topic: "/whit33r/kitchen/sonoff1"
#    brightness: true
    optimistic: false
    qos: 0


#switch:
#  platform: mqtt
#  name: "Switch"
#  state_topic: "whit33r/sonoff1"
#  command_topic: "/whit33r/kitchen/sonoff1"
#  payload_on: "ON"
#  payload_off: "OFF"
#  optimistic: true
#  qos: 1
 # retain: true
  #value_template: '{{ value.x }}'

switch:
  platform: mqtt
  name: "Folyosó Világítás"
  alias: "folyoso_light"
  state_topic: "home/sonoff/living_room/1/stat"
  command_topic: "home/sonoff/living_room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 2:
  platform: mqtt
  name: "Konyha Világítás"
  alias: "kitchen_light"
  state_topic: "home/sonoff/kitchen/1/stat"
  command_topic: "home/sonoff/kitchen/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 3:
  platform: mqtt
  name: "Szoba Fűtőpanel"
  alias: "heater test"
  state_topic: "home/sonoff/heater/1/stat"
  command_topic: "home/sonoff/heater/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 5:
  platform: mqtt
  name: "Fogyasztásmérő"
  state_topic: "home/sonoff/pwrHeater/1/stat"
  command_topic: "home/sonoff/pwrHeater/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 4:
  platform: mqtt
  name: "Szoba Világítás"
  alias: "szoba_vilagitas"
  state_topic: "home/sonoff/room/1/stat"
  command_topic: "home/sonoff/room/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

switch 5:
  platform: mqtt
  name: "test"
  state_topic: "home/sonoff/test/1/stat"
  command_topic: "home/sonoff/test/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true


#binary_sensor:
#  - platform: mqtt
#    state_topic: sensor/maindoor/motion
#    name: "Bejárati Ajtó"
#    alias_on: 'Nyitva'
#    alias_off: 'Zárva'
binary_sensor:
- platform: mqtt
  name: "Bejárati Ajtó"
  state_topic: "sensor/maindoor/motion"
  qos: 0
  payload_on: "Nyitva"
  payload_off: "Zárva"
  alias_on: 'Nyitva'
  alias_off: 'Zárva'
  device_class: opening

binary_sensor 2:
- platform: mqtt
  name: "Bejárati Ajtó Zár"
  state_topic: "sensor/maindoor/lock"
  qos: 0
  payload_on: "Nyitva"
  payload_off: "Zárva"
  alias_on: 'Nyitva'
  alias_off: 'Zárva'
  device_class: opening

binary_sensor 3:
- platform: mqtt
  name: "Mozgásérzékelő"
  state_topic: "sensor/maindoor/motionsen"
  qos: 0
  payload_on: "Nyitva"
  payload_off: "Zárva"
  alias_on: 'Mozgás'
  alias_off: 'Nincs Mozgás'
  device_class: motion




scene:
  - name: night_on
#    friendly_name: night_light
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 1
       rgb_color: [0, 0, 255]
  - name: night_off
#    friendly_name: night_light
    entities:
      light.szoba_vilagitas:
       state: off
  - name: dim_up_movie
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 250
       rgb_color: [255, 255, 255]
       transition: 5
  - name: dim_down_movie
    entities:
      light.szoba_vilagitas:
       state: on
       brightness: 2
       rgb_color: [0, 0, 255]
       transition: 5


group:
  default_view:
    view: yes
    icon: mdi:home 
    entities:
      - group.room
      - group.media_dev
      - group.kitchen
      - group.awesome_people
      - group.climate
  room:
    name: Szoba
    entities:
      - light.karacsonyfa
      - light.kis_karacsonyfa
      - light.szoba_hangulatfeny
      - switch.szoba_vilagitas
      - switch.test
      - sensor.szoba_lux
      - automation.When_lightoff_lockoff
      - automation.When_lighton_lockoff
#      - climate.study
#      - scene.dim_up_movie
#      - scene.dim_down_movie
#      - automation.media_player_pausedstopped
#      - automation.media_player_pausedstopped_
  kitchen:
    name: Konyha
#    view: no
    entities:
      - switch.konyha_vilagitas
      - switch.folyoso_vilagitas
      - binary_sensor.bejarati_ajto
      - binary_sensor.bejarati_ajto_zar
      - binary_sensor.mozgaserzekelo
#  upstairs:
#    name: Kids
#    icon: mdi:account-multiple
#    view: yes
#    entities:
#      - input_boolean.notify_home
#      - camera.demo_camera
#      - device_tracker.demo_paulus
#      - group.garden
  climate:
    name: Hőmérséklet
    view: no
    entities:
      - sensor.homerseklet_szoba
      - sensor.homerseklet_konyha
      - sensor.homerseklet_kulso
      - climate.szoba_termosztat
      - switch.szoba_futopanel
      - switch.fogyasztasmero
      - sensor.volt
      - sensor.jelenlegi_teljesitmeny
      - sensor.ossz_fogyasztas
  media_dev:
    name: Média Eszközök
#    view: no
    entities:
      - media_player.kodi
 #     - media_player.spotify
 #     - media_player.yamaha_receiver
  awesome_people:
    name: Emberek
    view: no
    entities:
      - device_tracker.lg_g4lan
      - device_tracker.whit33r_samsung_s7lan
alexa:

intent_script: !include alexa_intents.yaml

# Text to speech
#tts:
#  - platform: google

automation: !include automation.yaml
script: !include scripts.yaml

